### PR TITLE
if user type a wrong project name they will be guided by help of bot

### PR DESCRIPTION
**Pull request by JisanAR03**
if your type wrong project name bot will provide a message preview

image

@arkid15r sir, please let me know , if there is any suggestion for me

### CODE REVIEW

**Review by arkid15r — COMMENTED** [review]
This bot is not going to have any other functionality than greeting the newcomers, right?

I believe this PR should be filed against [BTL Sammich](https://github.com/OWASP-BLT/BLT-Sammich/).

**Comment by JisanAR03** [comment]
> This bot is not going to have any other functionality than greeting the newcomers, right?
> 
> I believe this PR should be filed against [BTL Sammich](https://github.com/OWASP-BLT/BLT-Sammich/).

yes sir, I will add this slash to sammich

**Comment by arkid15r** [comment]
As we agreed this is Sammich's functionality.

**Comment by JisanAR03** [comment]
> As we agreed this is Sammich's functionality.

yes sure , I will add this on sammich project for sure

**Pull request closed without merging**
